### ISSUE TITLE
OCP4 Migration

### ISSUE THREAD

**Issue by esune** [bcgov/issuer-kit-demo-verifier-chat#23]
The services need to be migrated to OCP4, they are currently hosted in the `devex-von-*` namespace set in OCP3.

- the target namespace in OCP4 is `4a9599`
- The contents of the folder `/opt/app-root/src/data` on the `prod` instance of `dsc-chat-server` will need to be migrated to the new deployment. It is just a couple of text files, so I would just copy their contents over with vim rather than setting up a PVC migrator, but see what works best for you.
- The client app uses `*.vonx.io` vanity URLs: please coordinate the certificate and DNS entry settings with @WadeBarnes

**Comment by wadeking98** [comment]
I'm assuming the only NSP policies that need to be implemented are client -> server and server -> client? @esune

**Comment by WadeBarnes** [comment]
> I'm assuming the only NSP policies that need to be implemented are client -> server and server -> client? @esune

NSPs are typically defined in a single direction client -> server.  This allows the server to respond to the client requests, while blocking the server from making a request to the client.  Which is typically the desired behaviour.

**Comment by wadeking98** [comment]
dsc-chat up and running in ocp4
