### ISSUE TITLE
Demo deployment decommissioning

### ISSUE THREAD

**Issue by esune** [bcgov/issuer-kit-demo-verifier-chat#90]
In order to decommission the demo, we need to complete the following steps:
- [x] remove references from public-facing the [BC Digital Trust website](https://digital.gov.bc.ca/digital-trust/) (@alexgmetcalf )
- [x] spin down the deployments (@WadeBarnes / @esune )
- [x] remove configurations from OCP (@WadeBarnes / @esune / @rajpalc7 )
- [x] archive this repository (@WadeBarnes / @esune )
- [x] close this issue (@WadeBarnes / @esune )

**Comment by alexgmetcalf** [comment]
Mentions removed from website

**Comment by esune** [comment]
@WadeBarnes @rajpalc7 wallets have been backed-up and deployments spun down in all environments. Everything is ready for resources to be freed.

**Comment by nodlesh** [comment]
Related BC Wallet test infrastructure work ticket is here, https://app.zenhub.com/workspaces/bc-wallet-6148e7423fe04b001444e2bd/issues/gh/hyperledger/aries-mobile-test-harness/145
May start work on this April 1 (Next BC Wallet Sprint).
